"""HTML report generation for Fitbit sleep summaries."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd
from jinja2 import BaseLoader, Environment, select_autoescape
from plotly.io import to_html

from src.visualization.dashboard import SleepDashboard


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <style>
    :root {
      --bg: #f4f7fb;
      --panel: #ffffff;
      --ink: #1f2933;
      --muted: #52606d;
      --border: #d9e2ec;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      padding: 32px;
      background: linear-gradient(180deg, #eef4fa 0%, var(--bg) 100%);
      color: var(--ink);
      font-family: Arial, sans-serif;
    }
    .report {
      max-width: 1280px;
      margin: 0 auto;
    }
    .hero, .section, .metric {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 18px;
      box-shadow: 0 14px 34px rgba(15, 23, 42, 0.06);
    }
    .hero {
      padding: 28px;
      margin-bottom: 24px;
    }
    .hero h1, .section h2 {
      margin: 0 0 10px;
    }
    .meta {
      color: var(--muted);
      margin-top: 8px;
    }
    .metric-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
      margin: 24px 0;
    }
    .metric {
      padding: 18px;
    }
    .metric .label {
      font-size: 0.9rem;
      color: var(--muted);
      margin-bottom: 8px;
    }
    .metric .value {
      font-size: 2rem;
      font-weight: 700;
    }
    .section {
      padding: 24px;
      margin-bottom: 20px;
    }
    .chart-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 18px;
    }
    .chart-card {
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 12px;
      background: #fbfdff;
    }
    .chart-card h3 {
      margin: 0 0 10px;
      font-size: 1rem;
    }
    .recommendations {
      padding-left: 18px;
      margin: 0;
    }
    .recommendations li {
      margin-bottom: 10px;
    }
    .footer {
      color: var(--muted);
      font-size: 0.9rem;
      text-align: center;
      margin-top: 18px;
    }
  </style>
</head>
<body>
  <main class="report">
    <section class="hero">
      <h1>{{ title }}</h1>
      <p>{{ subtitle }}</p>
      <div class="meta">
        <span>User: {{ user_name }}</span>
        {% if report_date %}
        <span> | Report date: {{ report_date }}</span>
        {% endif %}
        {% if sleep_date %}
        <span> | Sleep date: {{ sleep_date }}</span>
        {% endif %}
      </div>
      <div class="metric-grid">
        {% for metric in metrics %}
        <article class="metric">
          <div class="label">{{ metric.label }}</div>
          <div class="value">{{ metric.value }}</div>
        </article>
        {% endfor %}
      </div>
    </section>

    <section class="section">
      <h2>Charts</h2>
      <div class="chart-grid">
        {% for chart in charts %}
        <article class="chart-card">
          <h3>{{ chart.title }}</h3>
          {{ chart.html | safe }}
        </article>
        {% endfor %}
      </div>
    </section>

    <section class="section">
      <h2>Recommendations</h2>
      {% if recommendations %}
      <ul class="recommendations">
        {% for item in recommendations %}
        <li><strong>{{ item.title }}</strong>: {{ item.message }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No recommendations available for this report.</p>
      {% endif %}
    </section>

    <div class="footer">Generated by the Fitbit Sleep Score System.</div>
  </main>
</body>
</html>
"""


@dataclass(slots=True)
class SleepReportGenerator:
    """Generate a standalone HTML sleep report from nightly data."""

    dashboard: SleepDashboard = field(default_factory=SleepDashboard)
    _environment: Environment = field(init=False, repr=False)

    def __post_init__(self) -> None:
        """Create a compact Jinja environment for report rendering."""

        self._environment = Environment(
            loader=BaseLoader(),
            autoescape=select_autoescape(default_for_string=True, enabled_extensions=("html",)),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate_html_report(
        self,
        *,
        user_name: str = "Fitbit User",
        summary: Any | None = None,
        sleep_scores: Any | None = None,
        sleep_stages: Any | None = None,
        heart_rate_data: Any | None = None,
        recommendations: Any | None = None,
        report_date: str | None = None,
        title: str = "Sleep Report",
        subtitle: str = "A nightly sleep quality summary generated from Fitbit-derived metrics.",
        output_path: str | Path | None = None,
    ) -> str:
        """Render the report and optionally write it to disk."""

        summary_frame = self._to_frame(summary if summary is not None else sleep_scores)
        score_frame = self._to_frame(sleep_scores if sleep_scores is not None else summary)
        recommendation_items = self._normalize_recommendations(recommendations, summary_frame)

        figures = self.dashboard.create_dashboard_figures(
            sleep_scores=score_frame,
            sleep_stages=sleep_stages,
            heart_rate_data=heart_rate_data,
            score_components=summary_frame if not summary_frame.empty else score_frame,
        )
        charts = [
            {"title": self._chart_title(name), "html": to_html(figure, full_html=False, include_plotlyjs="cdn")}
            for name, figure in figures.items()
        ]

        context = {
            "title": title,
            "subtitle": subtitle,
            "user_name": user_name,
            "report_date": report_date,
            "sleep_date": self._extract_sleep_date(summary_frame, score_frame),
            "metrics": self._build_metrics(summary_frame, score_frame),
            "charts": charts,
            "recommendations": recommendation_items,
        }

        html = self._environment.from_string(REPORT_TEMPLATE).render(**context)
        if output_path is not None:
            Path(output_path).write_text(html, encoding="utf-8")
        return html

    def _to_frame(self, data: Any | None) -> pd.DataFrame:
        """Normalize supported report inputs to a DataFrame."""

        if data is None:
            return pd.DataFrame()
        if isinstance(data, pd.DataFrame):
            return data.copy()
        if isinstance(data, dict):
            return pd.json_normalize([data], sep="_")
        if isinstance(data, list):
            return pd.json_normalize(data, sep="_")
        raise TypeError("Report inputs must be a DataFrame, dict, list, or None.")

    def _build_metrics(self, summary_frame: pd.DataFrame, score_frame: pd.DataFrame) -> list[dict[str, str]]:
        """Build the hero metric cards for the report."""

        source = summary_frame if not summary_frame.empty else score_frame
        if source.empty:
            return [
                {"label": "Sleep score", "value": "N/A"},
                {"label": "Duration", "value": "N/A"},
                {"label": "Efficiency", "value": "N/A"},
                {"label": "Recovery", "value": "N/A"},
            ]

        row = source.iloc[0]
        duration_minutes = self._safe_float(row.get("total_sleep_minutes"))
        hours = int(duration_minutes // 60) if duration_minutes else 0
        minutes = int(duration_minutes % 60) if duration_minutes else 0
        duration_label = f"{hours}h {minutes}m" if duration_minutes else "N/A"
        score_value = self._first_value(row, ("final_score", "overall_score", "sleep_score", "score"))
        efficiency = self._first_value(row, ("sleep_efficiency", "sleep_efficiency_score"))
        recovery = self._first_value(row, ("recovery_score",))

        return [
            {"label": "Sleep score", "value": self._format_metric(score_value)},
            {"label": "Duration", "value": duration_label},
            {"label": "Efficiency", "value": self._format_metric(efficiency, suffix="%")},
            {"label": "Recovery", "value": self._format_metric(recovery)},
        ]

    def _normalize_recommendations(
        self,
        recommendations: Any | None,
        summary_frame: pd.DataFrame,
    ) -> list[dict[str, str]]:
        """Flatten recommendation payloads to a renderable list."""

        if recommendations is None and not summary_frame.empty and "recommendations" in summary_frame.columns:
            recommendations = summary_frame.iloc[0]["recommendations"]

        if recommendations is None:
            return []
        if isinstance(recommendations, pd.Series):
            recommendations = recommendations.iloc[0] if not recommendations.empty else []
        if isinstance(recommendations, dict):
            recommendations = [recommendations]

        normalized: list[dict[str, str]] = []
        for item in recommendations or []:
            if not isinstance(item, dict):
                normalized.append({"title": "Recommendation", "message": str(item)})
                continue
            normalized.append(
                {
                    "title": str(item.get("title", "Recommendation")),
                    "message": str(item.get("message", "")),
                }
            )
        return normalized

    def _extract_sleep_date(self, summary_frame: pd.DataFrame, score_frame: pd.DataFrame) -> str | None:
        """Return a displayable sleep date when present."""

        for frame in (summary_frame, score_frame):
            if frame.empty:
                continue
            for column in ("score_date", "dateOfSleep", "session_date", "date"):
                if column in frame.columns:
                    value = pd.to_datetime(frame.iloc[0][column], errors="coerce")
                    if pd.notna(value):
                        return value.strftime("%Y-%m-%d")
        return None

    def _chart_title(self, chart_key: str) -> str:
        """Map internal chart keys to display titles."""

        return chart_key.replace("_", " ").title()

    def _first_value(self, row: pd.Series, columns: tuple[str, ...]) -> Any:
        """Return the first non-null value across candidate columns."""

        for column in columns:
            if column in row and pd.notna(row[column]):
                return row[column]
        return None

    def _format_metric(self, value: Any, *, suffix: str = "") -> str:
        """Format display metrics consistently."""

        numeric = self._safe_float(value)
        if value is None or pd.isna(value):
            return "N/A"
        return f"{numeric:.1f}{suffix}"

    def _safe_float(self, value: Any) -> float:
        """Convert a scalar-like value to float when possible."""

        try:
            return float(value)
        except (TypeError, ValueError):
            return 0.0


__all__ = ["SleepReportGenerator"]
